<!--
php/renewal-form.php
By Matthew DiMatteo, Children's Technology Review

This file contains the renewal form, which loads the secure transaction portal through authorize.net containing the subscription renewal item
It is included in the files 'php/profiles/subscriber/section-subscription.php' and 'php/content/content-renew.php'

The form name and action are generated by authorize.net
The "LinkId" input associates the form with the specific item, in this case the subscription renewal for $50 ($10 off)
The LinkId values for all authorize.net items can be found in the 'subbies.fmp12' database via the 'promocodes' and 'authitems' layouts
This form is wrapped within a div set to display:none and has the element id 'renewal-form' for use by buttons
-->
<div class = "hide">
	<form id="renewal-form" name="PrePage" method="POST" action="https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx" target="_blank">
		<input type = "hidden" name = "LinkId" value = "f021e91f-0880-4ced-8f29-4f7c43d46b67"><!-- see 'subbies.fmp12' promocodes/authitems layouts -->
	</form><!-- /#renewal-form -->
</div><!-- /.hide -->